import type { UiInteractionContract } from "../uic/schema";

export const moveEditorNote376To378To359: UiInteractionContract = {
  id: "UIC-CLEAN-001",
  title: "移动 Editor’s Note 后刷新章节标题与变动行",
  area: "清洗工作区 / 章节标题 / 变动行",
  intent: "验证源码中移动一段包含 Markdown 标题的内容后，章节标题模块与变动行审计表都能准确反映变化。",
  automation: "browser",
  fixture: {
    mode: "ui-test",
    source: "source.md",
    baseline: "source",
  },
  preconditions: [
    "使用固定 Buffett’s Alpha source.md 作为原稿和初始 working。",
    "清洗工作区已初始化。",
    "章节标题、变动行模块可切换。",
  ],
  steps: [
    {
      action: "moveLines",
      startLine: 376,
      endLine: 378,
      beforeLine: 359,
      note: "将 ## Editor’s Note、空行及 Submited... 移到第 359 行之前。",
    },
  ],
  expectations: [
    {
      kind: "moduleNotice",
      module: "变动行",
      text: "+4",
      flashing: true,
      note: "文本块移动后，变动行模块标签必须闪烁并提示本次新增 4 条变动。",
    },
    {
      kind: "gridRow",
      module: "章节标题",
      line: 359,
      text: "## Editor’s Note",
      changed: true,
      note: "移动后的二级标题必须在章节标题表出现，并标记为与原稿不同。",
    },
    {
      kind: "gridRow",
      module: "变动行",
      line: 359,
      change: "新增",
      text: "## Editor’s Note",
      navigable: true,
      note: "新增行必须可以点击预览跳转到 working 中的新位置。",
    },
    {
      kind: "gridRow",
      module: "变动行",
      line: 361,
      change: "新增",
      text: "Submited 24 April 2018 Accepted 15 June 2018 by Stephen J. Brown",
      navigable: true,
      note: "新增正文行必须可以点击预览跳转到 working 中的新位置。",
    },
    {
      kind: "gridRow",
      module: "变动行",
      line: 379,
      change: "删除",
      text: "## Editor’s Note",
      deletedStyle: true,
      nonNavigable: true,
      note: "删除行必须变灰并带删除线，点击后不能跳转到工作稿。",
    },
    {
      kind: "gridRow",
      module: "变动行",
      line: 380,
      change: "删除",
      text: "Submited 24 April 2018 Accepted 15 June 2018 by Stephen J. Brown",
      deletedStyle: true,
      nonNavigable: true,
      note: "删除正文行必须保留审计内容，但不能提供源码定位。",
    },
    {
      kind: "moduleNoticeCleared",
      module: "变动行",
      note: "进入变动行模块后，+4 未读提示必须清除。",
    },
  ],
  invariants: [
    "文本块移动产生新的 diff 后，变动行标签必须提供可见反馈：闪烁并显示 +行数。",
    "用户进入变动行模块后，+行数提示应清除。",
    "移动标题前没有空行时，Markdown 标题仍必须被识别。",
    "移动操作不得改变被移动三行本身的文本内容。",
    "变动行不得因为非法断行自动候选范围重叠而吞掉真实 diff。",
    "变动行中的新增和修改记录必须仍可跳转到 working 对应位置。",
    "变动行中的删除记录必须以灰色删除线呈现，且不能跳转到已不存在的工作稿位置。",
  ],
  evidence: {
    coreTest: "src/chapterReviewApplication.test.ts",
    browserTest: "ui-spikes/integration/tests/ui.spec.ts",
  },
  tags: ["chapter-title", "diff", "move-lines", "ag-grid", "regression"],
};
