import type { UiInteractionContract } from "../uic/schema";

export const uiDebugSaveReenter: UiInteractionContract = {
  id: "UIC-DEBUG-009",
  title: "功能调试：保存标定并重入自动加载",
  area: "真实页面 / 功能调试 / 保存标定 / 重入",
  intent: "用一个功能调试入口验证正文与人工标定同时保存，并在离开后重入同一章节时自动恢复。",
  automation: "browser",
  fixture: {
    mode: "production-debug",
    source: "source.md",
    baseline: "source",
  },
  preconditions: [
    "直接加载真实 / 页面。",
    "功能调试内部使用固定章节 fixture 和内存持久化，不写真实 Google Drive。",
    "保存前会同时修改第 26 行正文，并把 <sup>1</sup> 注释引用标为已忽略。",
  ],
  steps: [
    { action: "clickControl", controlId: "ui-debug-toggle", note: "打开功能调试。" },
    {
      action: "clickControl",
      controlId: "ui-debug-save-reenter",
      note: "一次点击自行完成修改、标定、保存、离开和重入；runner 不得补做业务动作。",
    },
    { action: "clickControl", controlId: "ui-debug-toggle", note: "仅用于最终检查功能调试节点状态。" },
  ],
  expectations: [
    {
      kind: "featureDebugProgress",
      state: "passed",
      visible: false,
      completedSteps: 5,
      title: "5/5 通过",
      note: "五步保存/重入流程必须全部自行完成，并在通过结果短暂显示后自动收起步骤面板。",
    },
    { kind: "workspaceVisible", workspace: "cleaning" },
    { kind: "moduleActive", module: "注释" },
    {
      kind: "workingContains",
      text: "Much has been said and written about Warren Buffett and his ",
      note: "重入后必须自动加载保存后的 working，而不是原始 OCR 文本。",
    },
    {
      kind: "gridLineAbsent",
      module: "注释",
      line: 26,
      note: "重入后已忽略的第 26 行注释引用仍应隐藏。",
    },
    {
      kind: "controlState",
      controlId: "undo-workbench",
      visible: true,
      disabled: true,
      text: "撤销",
      note: "重入是新会话，Undo 历史必须清空。",
    },
    {
      kind: "controlState",
      controlId: "redo-workbench",
      visible: true,
      disabled: true,
      text: "重做",
      note: "重入是新会话，Redo 历史必须清空。",
    },
    {
      kind: "controlState",
      controlId: "save-calibration",
      visible: true,
      disabled: false,
      text: "保存标定",
      note: "重入章节后保存标定仍应可用。",
    },
    {
      kind: "controlState",
      controlId: "status",
      visible: true,
      text: "已自动加载保存后的 working 与 sidecar",
    },
    {
      kind: "controlState",
      controlId: "ui-debug-save-reenter",
      visible: true,
      disabled: true,
      text: "保存标定 / 重入加载",
      note: "执行完成后只禁用自身。",
    },
    {
      kind: "controlState",
      controlId: "ui-debug-undo-redo",
      visible: true,
      disabled: false,
      text: "撤销 / 重做",
    },
  ],
  invariants: [
    "功能调试只占一个保存/重入入口。",
    "功能调试不得写真实 Google Drive。",
    "保存必须同时包含 working、reviewRows 和 annotationPairs。",
    "离开前必须故意恢复未修改内存基线，以证明重入结果来自已保存状态。",
    "重入必须调用正常产品 loadDriveChapter 路径。",
    "人工已忽略标定不得因重新扫描而丢失。",
    "重入新会话必须清空 Undo / Redo 历史。",
    "成功完成后步骤进度面板必须自动收起；失败时应保留面板用于诊断。",
  ],
  evidence: {
    coreTest: "src/chapterWorkspaceApplication.test.ts",
    browserTest: "ui-spikes/integration/tests/ui.spec.ts",
  },
  tags: ["feature-debug", "save", "calibration", "reenter", "persistence", "production-route"],
};
