import type { UiInteractionContract } from "../uic/schema";

export const uiDebugInitialize: UiInteractionContract = {
  id: "UIC-DEBUG-002",
  title: "功能调试初始化恢复工作稿与界面",
  area: "顶部工作区导航 / 功能调试",
  intent: "验证执行标准调试样例后，初始化节点可以把工作稿和清洗界面恢复到稳定初始状态。",
  automation: "browser",
  fixture: {
    mode: "ui-test",
    source: "source.md",
    baseline: "source",
  },
  preconditions: [
    "工作稿初始等于 source.md。",
  ],
  steps: [
    { action: "clickControl", controlId: "ui-debug-toggle" },
    { action: "clickControl", controlId: "ui-debug-line-menu", note: "先完整执行行号菜单样例，使其进入已执行状态。" },
    { action: "clickControl", controlId: "ui-debug-toggle", note: "重新打开功能调试下拉。" },
    { action: "clickControl", controlId: "ui-debug-initialize", note: "恢复工作稿、界面和所有调试节点初始状态。" },
  ],
  expectations: [
    { kind: "controlState", controlId: "ui-debug-menu", visible: true },
    {
      kind: "controlState",
      controlId: "ui-debug-move-source-block",
      visible: true,
      disabled: false,
      text: "移动源文本块",
      note: "初始化后移动样例的前置条件恢复，节点重新可用。",
    },
    {
      kind: "controlState",
      controlId: "ui-debug-line-menu",
      visible: true,
      disabled: false,
      text: "行号菜单",
      note: "初始化后行号菜单样例必须重新可执行。",
    },
    {
      kind: "controlState",
      controlId: "ui-debug-edit-text-line",
      visible: true,
      disabled: false,
      text: "修改文本行",
      note: "初始化后修改文本行样例必须重新可执行。",
    },
    {
      kind: "controlState",
      controlId: "ui-debug-ignore-line-type",
      visible: true,
      disabled: false,
      text: "行类型：已忽略",
      note: "初始化后统一已忽略样例必须重新可执行。",
    },
    {
      kind: "controlState",
      controlId: "ui-debug-undo-redo",
      visible: true,
      disabled: false,
      text: "撤销 / 重做",
      note: "初始化后撤销 / 重做完整样例必须重新可执行。",
    },
    {
      kind: "controlState",
      controlId: "ui-debug-save-reenter",
      visible: true,
      disabled: false,
      text: "保存标定 / 重入加载",
      note: "初始化后保存标定 / 重入加载样例必须重新可执行。",
    },
    {
      kind: "controlState",
      controlId: "undo-workbench",
      visible: true,
      disabled: true,
      text: "撤销",
      note: "初始化必须清空 Undo 历史。",
    },
    {
      kind: "controlState",
      controlId: "redo-workbench",
      visible: true,
      disabled: true,
      text: "重做",
      note: "初始化必须清空 Redo 历史。",
    },
    {
      kind: "workingEqualsSource",
      note: "初始化必须把 working 完整恢复为 source.md。",
    },
    { kind: "workspaceVisible", workspace: "cleaning" },
    { kind: "moduleActive", module: "章节标题" },
    { kind: "moduleNoticeCleared", module: "变动行" },
  ],
  invariants: [
    "初始化不得修改 source.md 基线。",
    "初始化必须清除调试操作产生的变动提示。",
    "初始化后工作稿、模块和全部功能调试节点状态必须恢复，可再次复现任一标准样例。",
  ],
  evidence: {
    browserTest: "ui-spikes/integration/tests/ui.spec.ts",
  },
  tags: ["ui-debug", "reset", "fixture", "repeatable"],
};
