import type { UiInteractionContract } from "../uic/schema";

export const uiDebugEditTextLine: UiInteractionContract = {
  id: "UIC-DEBUG-006",
  title: "修正第 26 行 OCR 文本并反映到变动行",
  area: "真实页面 / 顶部功能调试 / 变动行 / 注释",
  intent: "精确修正第 26 行开头的 OCR 错误；只把正文修改反映到变动行，同时保留未被修改的 <sup>1</sup> 注释引用。",
  automation: "browser",
  fixture: {
    mode: "production-debug",
    source: "source.md",
    baseline: "source",
  },
  preconditions: [
    "加载真实 / 页面，不使用 ?ui-test=1。",
    "功能调试使用固定 fixture，不写真实 Google Drive。",
    "第 26 行包含指定 OCR 片段，并在行尾保留 <sup>1</sup> 注释引用。",
  ],
  steps: [
    { action: "clickControl", controlId: "ui-debug-toggle", note: "打开功能调试下拉。" },
    {
      action: "clickControl",
      controlId: "ui-debug-edit-text-line",
      note: "一次点击精确替换第 26 行指定 OCR 片段，并切到变动行模块。",
    },
    {
      action: "clickControl",
      controlId: "ui-debug-toggle",
      note: "重新打开调试下拉，核对只灰掉修改文本行节点。",
    },
  ],
  expectations: [
    { kind: "workspaceVisible", workspace: "cleaning" },
    {
      kind: "sourceLineActive",
      line: 26,
      note: "执行完成后源码光标必须停在第 26 行。",
    },
    {
      kind: "controlState",
      controlId: "ui-debug-edit-text-line",
      visible: true,
      disabled: true,
      text: "修改文本行",
      note: "执行后只禁用修改文本行节点自身。",
    },
    {
      kind: "controlState",
      controlId: "ui-debug-move-source-block",
      visible: true,
      disabled: false,
      text: "移动源文本块",
    },
    {
      kind: "controlState",
      controlId: "ui-debug-line-menu",
      visible: true,
      disabled: false,
      text: "行号菜单",
    },
    {
      kind: "moduleNotice",
      module: "变动行",
      text: "+1",
      flashing: true,
      note: "这次单行正文修改必须给出变动行 +1。",
    },
    {
      kind: "gridRow",
      module: "变动行",
      line: 26,
      text: "Much has been said and written about Warren Buffett and his investment style",
      change: "修改",
      owner: "未归类",
      navigable: true,
      note: "第 26 行必须作为修改记录出现；修改范围没有碰到注释号，所以归属模块为未归类。",
    },
    {
      kind: "gridRow",
      module: "注释",
      line: 26,
      text: "<sup>1</sup>",
      lineType: "注释引用",
      navigable: true,
      note: "行尾 <sup>1</sup> 没有被修改，原有注释引用必须继续保留在注释表。",
    },
    {
      kind: "gridLineAbsent",
      module: "嵌入块",
      line: 26,
      note: "单独的数字 <sup>1</sup> 注释引用不得让整行正文误判为嵌入块。",
    },
    {
      kind: "gridLineAbsent",
      module: "章节标题",
      line: 26,
    },
    {
      kind: "gridLineAbsent",
      module: "非法断行",
      line: 26,
    },
  ],
  invariants: [
    "只能替换用户指定的 OCR 片段，不得整行重写。",
    "替换前后第 26 行其余正文保持原样。",
    "行尾 <sup>1</sup> 必须保留。",
    "变动行必须记录第 26 行为修改。",
    "变动归属按实际修改字符范围判断；未触碰 <sup>1</sup> 时不得归属注释。",
    "原有 <sup>1</sup> 注释候选必须继续存在于注释模块。",
    "数字 <sup>1</sup> 注释引用本身不得把普通正文归入嵌入块。",
    "执行后只禁用修改文本行节点；其他调试节点保持原状态。",
    "初始化后所有调试节点必须重新可执行。",
  ],
  evidence: {
    browserTest: "ui-spikes/integration/tests/ui.spec.ts",
    coreTest: "src/scanner.test.ts",
  },
  tags: ["ui-debug", "production-route", "changed-lines", "annotation", "range-ownership", "ocr-correction"],
};
